### ISSUE TITLE
undefined method `write_to_file'

### ISSUE THREAD

**Issue by oddclot** [riboseinc/despeck#21]
Greetings!

I'm using despeck 0.3.0 with ruby 2.7.0, and after checking and rechecking any dependencies, I get this error when trying to use despeck remove with some PDF files:

`/var/lib/gems/2.7.0/gems/despeck-0.3.0/lib/despeck/pdf_tools.rb:49:in` `block in for_each_image_file': undefined method `write_to_file' for nil:NilClass `(NoMethodError)`

As I'm not completely familiarized with Ruby yet, I'm not sure whether the problem is in the write_to_file method, or in that the program is not assigning the proper class to each image (and so it cannot apply the write_to_file).

Any ideas what should I do to fix this?

Thanks!

**Comment by ronaldtse** [comment]
@oddclot thanks for the report! @nattfodd do you have time for this?

**Comment by ronaldtse** [comment]
@oddclot I believe this is fixed , despect now works with Ruby 2.7. Please re-open if it's still an issue. Thanks!
